name: flutter_e_commerce_c11_online
description: A new Flutter application.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  cached_network_image:
  carousel_slider_plus:
  flutter_screenutil:
  flutter_slidable:
  auto_size_text:
  colornames:
  flutter_svg:
  flutter_native_splash:
  readmore: ^2.2.0
  smooth_page_indicator:




  cupertino_icons: ^1.0.2
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.4
  flutter_bloc: ^9.1.1
  injectable: ^2.5.0
  get_it: ^8.0.3
  injectable_generator: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.5.4


flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/svg_images/



  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-.ttf

