name: flutter_e_commerce_c11_online
description: A new Flutter application.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  cached_network_image: ^3.3.1
  carousel_slider_plus: ^7.1.0
  flutter_screenutil: ^5.9.0
  flutter_slidable: ^3.1.0
  auto_size_text: ^3.0.0
  colornames: ^0.1.0
  flutter_svg: ^2.0.10+1
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0
  readmore: ^2.2.0
  cupertino_icons: ^1.0.2
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.4
  flutter_bloc: ^9.1.1
  injectable: ^2.5.0
  get_it: ^8.0.3
  injectable_generator: ^2.7.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.5.4


flutter:
  generate: true
  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/
    - assets/svg_images/



  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-.ttf

